### ISSUE TITLE
Restructure project

### ISSUE THREAD

**Issue by barakugav** [barakugav/FDML#6]
fdml
├── fdml-core
│   ├── include
│   │   └── fdml
│   │       └── *.hpp
│   ├── src
│   │   └── *.cpp
│   ├── cmds
│   │   ├── fdml_daemon
│   │   └── fdml_cli
│   ├── example
│   │   └── squere_room
│   ├── tests
│   │   └── ...
│   └── CMakeLists.txt
│
├── fdml-py
│   ├── src
│   │   ├── export_polygon_2.cpp
│   │   └── ...
│   └── CMakeLists.txt
│
├── fdml-gui
│   └── fdmlgui
│       ├── locator.py
│       └── ...
│
├── scripts
│   ├── get_boost.py
│   ├── matlab
│   └── locate.py
└── CMakeLists.txt

**Comment by efifogel** [comment]
What you refer to is the source tree.
When someone builds and *installs* FDML, certain files get installed into
the target directory.
The structure of the src tree and the target tree are completely different
as they serve different purposes.
For example, the source tree structure should enable convenient build of
GFML, while the target tree structure should enable convenient build of
other programs linking with FDML. There are other considerations.
When you type 'make install' you get the target tree structure below.
I still need to add some code to install the cgalpy.pyd and cgalpy.....whl
files.

├── bin:
│fdml_cli*  fdml_daemon*
├── include/fdml:
│bindings_types.hpp, Hash_rational_point.hpp, retcode.hpp, closer_edge.hpp,
json_utils.hpp, trapezoider.hpp, .....
├── lib:
│libfdml.so@  libfdml.so.1@  libfdml.so.1.0.0  Python./
| ├── cmake/fdml/
| | FDMLConfig.cmake  FDMLTargets.cmake FDMLConfigVersion.cmake
 FDMLTargets-release.cmake
| ├── Python/dist-packages:
| | fdml.pyi
   ____  _        ____             _
  /_____/_) o    /__________  __  //
 (____ (   (    (    (_/ (_/-(-'_(/
                         _/
